# Generated by Django 2.1.7 on 2019-03-10 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190310_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('inappropriate_content', models.BooleanField(verbose_name='Flag as inappropriate')),
                ('blogpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogPost')),
            ],
        ),
    ]
